const config = {
    introMessages: [
        `王樱迪是哈儿~`,
        `王樱迪是哈儿<br/>王樱迪是哈儿<br/>...`,
        `王樱迪是哈儿：<br/><span class='highlight'>王樱迪是哈儿奖</span><br/>王樱迪是哈儿`
    ],
    emojiList: ['🎂', '🎉', '🎁', '🎈', '🍰', '🧧'],
    contactPerson: '茶某',
    prizes: {
    '奖项1': { description: '欢快的歌', icon: '🎬' },
    '奖项2': { description: '伤心的歌', icon: '🎟️' },
    '奖项3': { description: 'R&B', icon: '💸' },
    '奖项4': { description: '爵士', icon: '📸' },
    '奖项5': { description: '情歌', icon: '🌠' },
    '奖项6': { description: '古风', icon: '🔁' },
    '奖项7': { description: '小众', icon: '🎹' },
    '奖项8': { description: '摇滚', icon: '🎤' },
    '奖项9': { description: '说唱', icon: '📺' },
    '奖项10': { description: '带天气的', icon: '📱' },
    '奖项11': { description: '带动物的', icon: '📼' },
    '奖项12': { description: '粤语', icon: '🔥' },
    '奖项13': { description: '电子舞曲', icon: '⚡' },
    '奖项14': { description: '民谣', icon: '🌿' },
    '奖项15': { description: 'K-Pop', icon: '🇰🇷' },
    '奖项16': { description: '日系动漫', icon: '🌸' },
    '奖项17': { description: '励志正能量', icon: '💪' },
    '奖项18': { description: '失恋情歌', icon: '💔' },
    '奖项19': { description: '校园青春', icon: '🎒' },
    '奖项20': { description: '旅行主题', icon: '✈️' },
    '奖项21': { description: '复古80s', icon: '📼' },
    '奖项22': { description: '国风新韵', icon: '🐉' },
    '奖项23': { description: '英文经典', icon: '🇬🇧' },
    '奖项24': { description: '深夜emo', icon: '🌙' },
    '奖项25': { description: '闽南语', icon: '🎉' },
    '奖项26': { description: '治愈系', icon: '🫶' },
    '奖项27': { description: '带食物的歌', icon: '🍕' },
    '奖项28': { description: '电影原声', icon: '🎥' },
    '奖项29': { description: '节日氛围', icon: '🎄' },
    '奖项30': { description: '自由发挥！', icon: '🌈' }
    }
};
